services:
    dmzx.username.listener:
        class: dmzx\username\event\listener
        arguments:
            - @template
            - @dbal.conn
        tags:
            - { name: event.listener }